#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

js_sources=(
  src/js/00-core.js
  src/js/05-icons.js
  src/js/10-style-mask-panels.js
  src/js/20-settings-host.js
  src/js/25-native-bridge-server.js
  src/js/26-version-update.js
  src/js/30-filter-selection.js
  src/js/40-timeline-layout.js
  src/js/50-keyframes-render.js
  src/js/60-sync-context-menus.js
  src/js/70-interaction-playback.js
  src/js/80-command-palette.js
  src/js/90-ease-panel.js
  src/js/95-mass-edit-panel.js
  src/js/96-text-animation-panel.js
  src/js/97-timing-order-panel.js
  src/js/100-panels-shortcuts-bootstrap.js
)

css_sources=(
  src/css/00-base-timeline.css
  src/css/10-dialogs-markers.css
  src/css/20-timeline-history.css
  src/css/30-keyframes-filters.css
  src/css/40-layout-native-theme.css
  src/css/50-modern-theme-controls.css
  src/css/60-style-anchor-panels.css
  src/css/70-style-context-refinements.css
  src/css/80-ease-panel.css
  src/css/85-mass-edit-panel.css
  src/css/86-text-animation-panel.css
  src/css/87-timing-order-panel.css
  src/css/90-command-panels.css
  src/css/95-quick-panel.css
)

# The manifest is the single source of truth for the version. Stamping it into
# the bundle means the UI can never disagree with what After Effects loaded.
panel_version="$(sed -n 's/.*ExtensionBundleVersion="\([^"]*\)".*/\1/p' CSXS/manifest.xml | head -1)"
if [[ -z "$panel_version" ]]; then
  echo "Could not read ExtensionBundleVersion from CSXS/manifest.xml" >&2
  exit 1
fi

build_bundle() {
  local output="$1"
  shift

  local temp
  temp="$(mktemp "${TMPDIR:-/tmp}/ae-panel-build.XXXXXX")"
  trap 'rm -f "$temp"' RETURN

  if [[ "$output" == *.js ]]; then
    printf '// Generated by scripts/build.sh from CSXS/manifest.xml - do not edit.\nconst TNT_VERSION = "%s";\n\n' "$panel_version" >> "$temp"
  fi

  for source in "$@"; do
    [[ -f "$source" ]] || {
      echo "Missing source module: $source" >&2
      exit 1
    }
    cat "$source" >> "$temp"
  done

  mv "$temp" "$output"
  trap - RETURN
}

build_bundle js/main.js "${js_sources[@]}"
build_bundle css/style.css "${css_sources[@]}"
cp index.html quick.html

echo "built: js/main.js (${#js_sources[@]} modules, v${panel_version})"
echo "built: css/style.css (${#css_sources[@]} modules)"
echo "built: quick.html"
