#!/usr/bin/env bash
# Regenerates icons/lucide.js from the published lucide-static package.
#
# The raw SVGs are ~7.9MB of XML boilerplate for 2,035 icons; stripped to their
# inner path data the whole set is ~420KB, so the entire library ships rather
# than a curated subset. That matters because users assign icons to their own
# quick-access buttons at runtime - the panel cannot know in advance which ones
# it needs.
#
# Lucide is ISC licensed. Run this to update to a newer release.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "resolving lucide-static..."
url="$(curl -sL --max-time 30 https://registry.npmjs.org/lucide-static \
  | python3 -c "import json,sys;d=json.load(sys.stdin);v=d['dist-tags']['latest'];print(d['versions'][v]['dist']['tarball'])")"
version="$(basename "$url" | sed 's/lucide-static-//;s/\.tgz//')"
echo "  version $version"

curl -sL --max-time 120 "$url" -o "$work/lucide.tgz"
tar xzf "$work/lucide.tgz" -C "$work"

python3 - "$work/package/icons" "$root/icons/lucide.js" "$version" <<'PY'
import glob, json, os, re, sys
src, out, version = sys.argv[1], sys.argv[2], sys.argv[3]
icons = {}
for path in sorted(glob.glob(os.path.join(src, "*.svg"))):
    raw = open(path, encoding="utf-8").read()
    inner = re.sub(r"^.*?<svg[^>]*>|</svg>\s*$", "", raw, flags=re.S).strip()
    inner = re.sub(r"\s+", " ", inner)
    icons[os.path.basename(path)[:-4]] = inner
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/fetch-icons.sh - do not edit.\n")
    f.write(f"// Lucide {version}, ISC licensed. https://lucide.dev\n")
    f.write("// Inner SVG markup only; every icon is drawn on a 24x24 grid with a\n")
    f.write("// 2px round-capped stroke, coloured through currentColor.\n")
    f.write("window.TNT_LUCIDE = ")
    json.dump(icons, f, separators=(",", ":"), sort_keys=True)
    f.write(";\n")
print(f"  wrote {len(icons)} icons -> {os.path.relpath(out, os.path.dirname(os.path.dirname(out)))}")
PY

echo "done: $(du -h "$root/icons/lucide.js" | cut -f1)"
